version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
